### ISSUE TITLE
Invalid client_id

### ISSUE THREAD

**Issue by p2wn** [davidfegyver/kreta-api#1]
Valaki tudja mi lett az új client_id ami szükséges a request elküldéséhez?

**Comment by PiciAkk** [comment]
lehet, hogy ezzel nem mondok újat, de a repo legutolsó commitja 2 éves, tehát valószínűleg minden outdated

**Comment by PiciAkk** [comment]
még nonce sincs ebben az API dokumentációban.

ajánlanék jobbat, de nincsen xdd. javaslom, hogy lépj be a CWD és/vagy a Filc Napló Discord szerverre, ott meg tudják válaszolni a kérdéseidet

also: egy "önmagát dokumentáló", up-to-date KRÉTA API wrapper pl. a [kretén](https://github.com/filc/kreten)

**Comment by p2wn** [comment]
pár hónappal ezelőtt sikerült lekérnem a bearer token-t nem másik apival
de azóta azok is elromlottak.

**Comment by p2wn** [comment]
de a client_id ami megvan adva jelenleg https://github.com/filc/kreten ebben is nem jó többé.

**Comment by PiciAkk** [comment]
igen, Filcen is többen problémáznak, hogy nem megy a bejelentkezés/jegyek lekérése: akkor ez a probléma

valószínűleg a KRÉTA kedves munkatársai megint valamit baszogtattak az API-n ~~(lehet, hogy van köztünk egy KRÉTÁS kém, mert pont ma beszéltünk arról a Filc++ szerverén, hogy az API már régóta nem változott)~~

**Comment by PiciAkk** [comment]
egyébként tudom **újra** ajánlani a [Filc Napló szerverét](https://filcnaplo.hu/discord), ahol épp erről a témáról van szó

**Comment by PiciAkk** [comment]
Gondolom, hogy ezt már te is észrevetted, de annon fixelt.

Az új clientid `kreta-ellenorzo-mobile-android`

**Comment by PiciAkk** [comment]
@davidfegyver close this issue pls
